nginx:
  image: nginx
  links:
    - web:web
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - updateme_data
web: &web
  build: .
  dockerfile: Dockerfile.web
  expose:
    - "3000"
  links:
    - postgres:db
    - redis:redis
  environment: &envs
    RACK_ENV: development
    RAILS_ENV: development
    REDIS_HOST: redis
    REDIS_PORT: 6379
  volumes:
    - ./updateme-web:/app
  volumes_from:
    - updateme_data
worker:
  <<: *web
  dockerfile: Dockerfile.worker
  expose: []
cron:
  build: .
  dockerfile: Dockerfile.cron
  links:
    - web:web
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: password
  volumes_from:
    - updateme_data
redis:
  image: redis
