FROM node:5.4.0

# Mount your dev assets dir
VOLUME /var/build/input
# Mount your assets loading dir
VOLUME /var/build/output

WORKDIR /var/build

COPY package.json /var/build/package.json

RUN npm install

COPY webpack.config.js /var/build/webpack.config.js
COPY .eslintrc /var/build/.eslintrc

CMD npm run dev
